# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [4]:
a = np.arange(10)
a.size

10

#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
b = np.arange(10)
b[4] = 1
b

array([0, 1, 2, 3, 1, 5, 6, 7, 8, 9])

#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
c = np.arange(10, 49)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [9]:
d = c[::-1]
d

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [20]:
a = np.array((1,2,0,0,4,0))
a.nonzero()

(array([0, 1, 4]),)

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [25]:
a = np.random.randint(1, 100, (3,3))
a

array([[65, 21, 76],
       [91,  6, 72],
       [10, 72, 88]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [30]:
a = np.random.randint(1, 100, (10,10))
print(a)
print('Max: ', a.max())
print('Min: ', a.min())

[[69 60 97 14 56 56 86 98 44 95]
 [25 12 31 33 54 29 19 18 65 97]
 [23 42 38 66 68 31 43 43 15 36]
 [32 91 18 30  1 83 62 79 27 75]
 [22 41  4 98 22 95 14 73 31 72]
 [56 83  3 59  2 35 42 35 72 34]
 [16 44 11 88 26 92 89 46 18 41]
 [ 6 75  4 87 56 95 77 66  8 25]
 [69 78 30 30 26 16 81 55 19 55]
 [25  1 80 39 54 17 85 20 68 60]]
Max:  98
Min:  1


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [32]:
a = np.random.randint(1, 100, 30)
np.mean(a)

47.6

#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [40]:
a = np.ones((3,3), dtype='int')
a[1,1] = 0
a

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [41]:
b = np.pad(a, pad_width=1, constant_values=0)
print(b)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 0 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [42]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [52]:
a = np.zeros((5,5), dtype='int')
a[[1,2,3,4],[0,1,2,3]] = 1
a[[2,3,4],[0,1,2]] = 2
a[[3,4],[0,1]] = 3
a[4,0] = 4
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [4, 3, 2, 1, 0]])

#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [75]:
n = 6 * 7 * 8
a = np.arange(n).reshape(6,7,8)
index = np.where(a == 100)
index

(array([1]), array([5]), array([4]))

#### 16. Normalize a 5x5 random matrix (★☆☆)

In [79]:
a = np.random.randint(1, 100, (5,5))
amax, amin = a.max(), a.min()
b = (a - amin)/(amax - amin)
b

array([[0.27272727, 0.53409091, 0.80681818, 1.        , 0.72727273],
       [0.32954545, 0.82954545, 0.43181818, 0.35227273, 0.86363636],
       [0.18181818, 0.60227273, 0.55681818, 0.68181818, 0.875     ],
       [0.40909091, 0.09090909, 0.93181818, 0.77272727, 0.        ],
       [0.18181818, 0.39772727, 0.63636364, 0.57954545, 0.5       ]])

#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [89]:
a = np.arange(0, 10)
for n in a:
    if n > 3 and n < 8:
        a[n] = n * -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 18. How to round away from zero a float array ? (★☆☆)

In [90]:
def round_array(x, y):
    return np.round(x, y)

test = np.array([12.33, 11.5, 0.2213])
print(round_array(test, 0))

[12. 12.  0.]


#### 19. Find common values between two arrays? (★☆☆)

In [93]:
np.intersect1d([1,4,3,3], [3,1,2,4])

array([1, 3, 4])

#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [95]:
# False

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [133]:
def generate_array():
    a = np.random.randint(100, size=10)
    return a

print(generate_array())

[ 2 51  6 38 46 28 68 31 21 80]


#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [136]:
a = np.random.rand(10)
a

array([0.70449949, 0.17152398, 0.28615918, 0.40881961, 0.26589369,
       0.68334307, 0.68340956, 0.78628561, 0.21437027, 0.58934392])

#### 23. Create a random vector of size 10 and sort it (★★☆)

In [137]:
a = np.random.rand(10)
b = np.sort(a)
b

array([0.11859795, 0.22033806, 0.24645982, 0.25910382, 0.28033278,
       0.28463351, 0.48707363, 0.75786063, 0.94506249, 0.99414168])

#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [138]:
np.array_equal([1,2],[1,2])

True

In [139]:
np.array_equal([1,2],[2,1])

False

#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [157]:
a = np.random.rand(10)
amax = a.max()
i = 0
for num in a:
    if num == amax:
        a[i] = 0
    i += 1
    
print(a)

[0.42258801 0.54862397 0.43006441 0.0906304  0.45424551 0.84926823
 0.         0.11527672 0.68864321 0.52779792]


#### 26. Find the closest value to random element in a vector? (★★☆)

In [174]:
arr = np.array([9, 7, 3, 1, 6, 8, 2])
x = 4
difference = np.absolute(arr-x)
index = difference.argmin()
print(arr[index])

3


#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

In [200]:
arr = np.array([1.,2.,3.,4.], dtype='float32')
print('Before:', arr, '| data type: ', arr.dtype)
print('CONVERTING!')
arr = arr.astype('int32')
print('After:', arr, '| data type: ', arr.dtype)

Before: [1. 2. 3. 4.] | data type:  float32
CONVERTING!
After: [1 2 3 4] | data type:  int32


#### 28. Sort an array by the nth column? (★★☆)

In [220]:
a = np.random.randint(1, 10, (3,3))

def sort_by_column_n(arr, n):
    b = arr[arr[:, n].argsort()]
    return b

sort_by_column_n(a, 0)

array([[1, 8, 7],
       [4, 4, 7],
       [9, 6, 7]])

#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

In [245]:
a = np.random.randint(0, 2, (3, 10))
print(a)
print((~a.any(axis=0)).any())

[[0 0 0 1 1 1 0 0 1 1]
 [0 1 0 1 0 1 1 1 0 0]
 [1 1 0 0 1 0 0 0 1 0]]
True


#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [247]:
arr = np.array([1,2,3,4,5])
z = 3
new_arr = np.zeros(len(arr) + (len(arr)-1)*(z))
new_arr[::z+1] = arr
print(new_arr)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 31. Swap two rows of an array? (★★★)

In [251]:
a = np.random.randint(1, 10, (4,4))
print('Before:\n', a)
a[[0, 2]] = a[[2, 0]]
print('After:\n', a)

Before:
 [[7 7 4 8]
 [2 7 6 8]
 [5 9 6 9]
 [2 5 3 8]]
After:
 [[5 9 6 9]
 [2 7 6 8]
 [7 7 4 8]
 [2 5 3 8]]


#### 32. How to negate a boolean value inside an array? (★★★)

In [273]:
a = np.array([True, False])
a = ~a
print(a)

[False  True]


#### 33. Find the most frequent value in an array?

In [276]:
a = np.array([1,2,3,4,1,1,2,3,4,1,1,1,1,2,3,1,2,3])
counts = np.bincount(a)
print(counts)
print(np.argmax(counts))

[0 8 4 4 2]
1


#### 34. Get the n largest values of an array (★★★)

In [278]:
a = np.array([2,0,4,5,7,2,9,6])

sorted_index_array = np.argsort(a)

sorted_array = a[sorted_index_array]

n = 1

print(sorted_array[-n:])

[9]


#### 35. Extract unique rows from a two dimensional array? (★★★)

In [279]:
a = np.array([[1,1,1,0,0,0],
              [0,1,1,1,0,0],
              [0,1,1,1,0,0],
              [1,1,1,0,0,0],
              [1,1,1,1,1,0]])

print(np.unique(a, axis=0))

[[0 1 1 1 0 0]
 [1 1 1 0 0 0]
 [1 1 1 1 1 0]]
