### Load in NumPy

In [1]:
import numpy as np

### The Basics

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
# Get Dimension
a.ndim

1

In [12]:
b.ndim

2

In [8]:
# Get Shape
a.shape

(3,)

In [13]:
b.shape

(2, 3)

In [14]:
# Get Type
a.dtype

dtype('int64')

In [15]:
# Get Size
a.itemsize

8

In [16]:
# Get Total Size
a.nbytes

24

### Accessing/Changing Specific Elements, Rows, Columns, Etc.

In [39]:
a = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
a.shape

(2, 7)

In [19]:
# Get a specific element [r, c]
a[1, 5]

13

In [20]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [22]:
# Getting fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [23]:
a[0, 1:-1:2]

array([2, 4, 6])

In [24]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [25]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


***

In [27]:
# 3-D example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
# Get Specific Element (work outside in)
b[0,1,1]

4

In [29]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [31]:
# Replace
b[:,1,:] = [[9,9],[8,8]]

In [32]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [34]:
# ALL 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
# ALL 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [38]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [40]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [41]:
# Initialize a matrix of random decimal numbers
np.random.rand(4,2)

array([[0.90944883, 0.24574965],
       [0.59593851, 0.49741915],
       [0.86830921, 0.27483269],
       [0.92974849, 0.75175489]])

In [65]:
# Random Integer Values
np.random.randint(-4,7, size=(3,3))

array([[-2, -4,  2],
       [-1, -2,  2],
       [-2,  4,  4]])

In [66]:
# The Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [78]:
output = np.ones((5,5))
# print(output)

z = np.zeros((3,3))
z[1,1] = 9
# print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### **Be careful when copying arrays!!!**

In [86]:
a = np.array([1,2,3])
# Make sure to use .copy()
b = a.copy()
b[0] = 100
print(b)

[100   2   3]


In [87]:
print(a)

[1 2 3]


### Mathematics

In [101]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [97]:
a += 2
a

array([3, 4, 5, 6])

In [98]:
a - 2

array([1, 2, 3, 4])

In [99]:
a * 2

array([ 6,  8, 10, 12])

In [100]:
a / 2

array([1.5, 2. , 2.5, 3. ])

In [102]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [103]:
a ** 2

array([ 1,  4,  9, 16])

In [104]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [105]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

In [108]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [110]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [111]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
np.min(stats)

1

In [117]:
np.max(stats, axis=1)

array([3, 6])

In [119]:
np.sum(stats)

21

In [122]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [126]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [130]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [135]:
# Horizonal stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

In [ ]:
# Load Data From File
file_data = np.genfromtxt('data.txt', delimiter=',')
# convert data from float to int
file_data = file_data.astype('int32')

In [ ]:
# Boolean Masking and Advanced Indexing
file_data[file_data > 50]

In [136]:
# You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [ ]:
np.any(file_data > 50, axis=0)